ready for review
therealloker/02-library pull request #1
Opened 2018-05-13 19:04 UTC by therealloker

2018-05-15 14:57 UTC, vladfirstblood requested changes

2018-05-15 14:57 UTC, VladLysiuk commented on Gemfile
> +# ruby=2.5.0
Лишний комментарий

2018-05-15 14:57 UTC, VladLysiuk commented on Gemfile
> +gem 'faker'
Лучше использовать ffaker, он быстрее

2018-05-15 14:57 UTC, VladLysiuk commented on main.rb
> +#seed data from Faker
Лишний комментарий, по названию метода и так понятно, что происходит
Кроме того, нужно добавлять пробел между `#` и текстом комментария

2018-05-15 14:57 UTC, VladLysiuk commented on main.rb
> +require_relative 'src/Library'
Файлы именуем используя snake case, т.е. начиная с маленькой буквы

2018-05-15 14:57 UTC, VladLysiuk commented on main.rb
> +#get data from file for another lib object
Лишний комментарий

2018-05-15 14:57 UTC, VladLysiuk commented on main.rb
> +Top 1 book orders: #{lib1.count_of_orders_book(1)}
Может стоит переименовать метод `count_of_orders_book`? Вне контекста не совсем понятно, что он делает

2018-05-15 14:57 UTC, VladLysiuk commented on main.rb
> +lib1.seed
lib_1, используем snake_case в именовании переменных

2018-05-15 14:57 UTC, VladLysiuk commented on main.rb
> +#puts "Who often take the books?: #{lib1.top_reader}"
Зачем эти комментарии?

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +require_relative 'Models/Order'
Про именование файлов писал выше

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +      @orders << Order.new(@books[book_id], @readers[reader_id])
Лучше использовать более строгие условия в конструкторе (я про класс Order, но в других классах тоже самое), мы можем легко перепутать порядок аргументов.
Можно использовать keyword arguments

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +  def seed
Методы для записи/чтения не совсем релевантны к классу библиотеки. Это не критично, но я бы вынес их в отдельный модуль, в котором бы хранились вспомогательные методы

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +      @orders << Order.new(@books[book_id], @readers[reader_id])
`@books[book_id]` может вернуть nil, если сгенерированное значение `books_id` превысит максимально допустимый индекс. Тоже самое с `@readers[reader_id]`

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +    data = {}
Мы можем упростить запись в файл? Это выглядит громоздко
Мы можем объявить дополнительный метод в классах, объекты которых нам нужно записывать в файл, например.
```ruby
class Author
  def to_s
    { name: self.name, biography: self.biography }
  end
end

```

```ruby
data[:authors] = @authors.map(&:to_s)
```

Это как вариант, может ты придумаешь что-то интереснее)

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +    File.open('src/Data.txt', 'w') { |file| file.write(data) }
Что будет, если этого файла не существует?)
А ещё этот файл пустой, посмотри внимательно

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +    got_data = eval(File.read('src/Data.txt'))
1. Почему `eval`?
2. Что будет, если этого файла не существует?)

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +      case key
Очень комплексная логика, которую можно попробовать упростить (например, с помощью метапрограммирования)

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +      @readers << Reader.new(name, email, city, street, house)
Использовать локальные переменные здесь не имеет смысла, мы зря выделяем память, лучше подставлять непосредственно выражение.

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +    count.max_by { |_k, v| v }.first
Это можно написать проще, посмотри, как работает метод `group_by`

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +    count.max_by { |_k, v| v }.first
Это можно написать проще, посмотри, как работает метод `group_by`

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +    top.dig(position - 1, 1)
Это можно написать проще, посмотри, как работает метод `group_by`

2018-05-15 14:57 UTC, VladLysiuk commented on src/Models/Author.rb
> +end
No newline at the end of file, исправь это в дальнейших файлах

2018-05-15 14:57 UTC, VladLysiuk commented on src/Library.rb
> +      @books << Book.new(book_title, author_name)
Мы связываем класс `Author` с `Book ` по имени автора?
Это неправильно и ненадёжно, нужно использовать композицию и хранить объект класса `Author` в атрибуте 
 `:author` класса `Book`

2018-05-15 19:03 UTC, fxqhyw commented on src/Library.rb
> +    got_data = eval(File.read('src/Data.txt'))
1. Благодаря eval распознаю считываемые данные, и преобразую из String в Hash. Так как была запись хэша в чистом виде в txt.

2018-05-15 19:33 UTC, fxqhyw commented on Gemfile
> +# ruby=2.5.0
Исправил

2018-05-15 19:34 UTC, therealloker commented on Gemfile
> +gem 'faker'
Спасибо, буду знать
Исправил

2018-05-15 19:34 UTC, therealloker commented on main.rb
> +#seed data from Faker
Исправил

2018-05-15 19:34 UTC, therealloker commented on main.rb
> +require_relative 'src/Library'
Исправил

2018-05-15 19:34 UTC, therealloker commented on main.rb
> +#get data from file for another lib object
Исправил

2018-05-15 19:35 UTC, therealloker commented on main.rb
> +Top 1 book orders: #{lib1.count_of_orders_book(1)}
Переименовал, надеюсь удачно)

2018-05-15 19:35 UTC, therealloker commented on main.rb
> +lib1.seed
Исправил

2018-05-15 19:36 UTC, therealloker commented on main.rb
> +#puts "Who often take the books?: #{lib1.top_reader}"
Не знаю)
Исправил

2018-05-15 19:36 UTC, therealloker commented on src/Library.rb
> +require_relative 'Models/Order'
Исправил

2018-05-15 19:36 UTC, therealloker commented on src/Library.rb
> +      @orders << Order.new(@books[book_id], @readers[reader_id])
Исправил

2018-05-15 19:36 UTC, therealloker commented on src/Library.rb
> +  def seed
Исправил

2018-05-15 19:37 UTC, therealloker commented on src/Library.rb
> +      @orders << Order.new(@books[book_id], @readers[reader_id])
Исправил

2018-05-15 19:38 UTC, therealloker commented on src/Library.rb
> +      @books << Book.new(book_title, author_name)
Исправил

2018-05-15 19:39 UTC, therealloker commented on src/Models/Author.rb
> +end
Исправил

2018-05-15 20:30 UTC, therealloker commented on src/Library.rb
> +    data = {}
Спасибо за напоминание про конструкцию &:
Исправил

2018-05-15 20:32 UTC, fxqhyw commented on src/Library.rb
> +      @readers << Reader.new(name, email, city, street, house)
Исправил

2018-05-15 20:52 UTC, fxqhyw commented on src/Library.rb
> +    File.open('src/Data.txt', 'w') { |file| file.write(data) }
В этом случае файл будет создан. Добавил возможность указывать имя файла. Нормально оставить такую логику для сохранения ?
Файл был пустой, потому что, я предполагал сначала запись туда сгенерированных  данный из Faker, а уже потом считывание.

2018-05-15 20:52 UTC, therealloker commented on src/Library.rb
> +    got_data = eval(File.read('src/Data.txt'))
2. Добавил исключение

2018-05-15 23:27 UTC, therealloker commented on src/Library.rb
> +    count.max_by { |_k, v| v }.first
Исправил

2018-05-15 23:27 UTC, therealloker commented on src/Library.rb
> +    count.max_by { |_k, v| v }.first
Исправил

2018-05-15 23:27 UTC, therealloker commented on src/Library.rb
> +    top.dig(position - 1, 1)
Исправил

2018-05-16 09:48 UTC, VladLysiuk commented on src/Library.rb
> +    File.open('src/Data.txt', 'w') { |file| file.write(data) }
@therealloker, это ок, но я бы использовал два файла: 
`input.txt` - для считывания данных, и `output.txt` - для сохранения (причём этот файл нужно создавать, если его не существует). 
Так у нас не будет зависимости в действиях (как было сейчас: сначала надо было записать, а потом считать)

2018-05-16 09:49 UTC, VladLysiuk commented on src/Library.rb
> +    got_data = eval(File.read('src/Data.txt'))
@therealloker, тебе надо конвернуть стркоу в хэш?
Можно испольовать так называемые conversion functions:
```ruby
Hash['{a: 1, b: 2}'] # => {a: 1, b: 2}
```

2018-05-16 10:10 UTC, vladfirstblood reviewed
Всё неплохо, есть незначительные замечания

2018-05-16 10:10 UTC, vladfirstblood commented on src/library.rb
> +require_relative 'work_with_file'
Лучше использовать имена существительные, а не глаголы при именовании модулей/классов (например, можешь назвать этот файл или `io_helpers` и модуль будет называться `IOHelpers`)

2018-05-16 10:10 UTC, vladfirstblood commented on src/library.rb
> +    count = @orders.each_with_object({}) do |order, h|
`group_by`?

2018-05-16 10:10 UTC, vladfirstblood commented on src/library.rb
> +  def top_book
`group_by`?

2018-05-16 10:10 UTC, vladfirstblood commented on src/library.rb
> +  def count_of_book_orders_in_position(position)
`group_by`?

2018-05-16 10:10 UTC, vladfirstblood commented on src/library.rb
> +      book_id = rand(@books.length - 1)
Забыл в прошлый раз написать: мне кажется, что лучше использовать в качестве имени не `book_id`, а `book_index`. Идентификаторов у нас всё-таки нету в приложении

2018-05-16 10:10 UTC, VladLysiuk commented on src/work_with_file.rb
> +  def save_to_file(file_name = "data.txt")
Лучше использовать одинарные кавычки в строках без интерполяции: `'data.txt'`

2018-05-16 10:10 UTC, VladLysiuk commented on src/work_with_file.rb
> +    unless File.exist?("src/data/#{file_name}.txt")
Этот фрагмент лучше переписать с использованием `File.open` и обернуть его в блок `begin/rescue/end`, где обработать исключение (в случае несуществующего файла)

2018-05-16 10:10 UTC, VladLysiuk commented on src/work_with_file.rb
> +    got_data = eval(File.read("src/data/#{file_name}.txt"))
Про `eval` уже писал, можно его заменить с помощью `Hash[]`

2018-05-16 10:10 UTC, VladLysiuk commented on src/work_with_file.rb
> +    got_data = eval(File.read("src/data/#{file_name}.txt"))
Давай переименуем просто в `data`

2018-05-16 10:10 UTC, VladLysiuk commented on src/work_with_file.rb
> +        value.each { |a| @authors << Author.new(a[:name], a[:biography]) }
Это работает?
`Author.new(a[:name], a[:biography]`
Разве не должно быть `Author.new(name: a[:name], biography: a[:biography])`?

2018-05-16 10:10 UTC, VladLysiuk commented on src/work_with_file.rb
> +        value.each do |order|
Здесь у тебя название переменной в блоке `order`, а в остальных случаях - просто буквы. Давай придерживаться одного стиля

2018-05-17 07:25 UTC, vladfirstblood approved these changes

2018-05-17 07:25 UTC, VladLysiuk commented on src/io_helpers.rb
> +    File.open("src/data/#{file_name}", 'w') { |f| f.write(self.to_yaml) }
@therealloker, как вариант:
```ruby
file_path = "src/data/#{file_name}"
begin
  File.open(file_path, 'w')
rescue # указать специфический класс исключения
  File.new(file_path, 'w')
end.write(self.to_yaml)

2018-05-17 07:26 UTC, VladLysiuk commented
Всё ок, можешь мержить)

2018-05-17 13:08 UTC, closed without merging